export const products = [
    {
      id: '1',
      name: 'iPhone 14 Pro Max',
      description: 'Apple’s latest iPhone with A16 Bionic chip and triple camera setup.',
      price: 1099.99,
      stock_quantity: 25,
      category_id: 'mobiles',
      brand: 'Apple',
      sku: 'APL-IP14PM',
      is_active: true,
      image: '/products/iphone14.png',
      created_at: '2024-01-01T10:00:00Z',
      updated_at: '2024-04-01T12:00:00Z',
    },
    {
      id: '2',
      name: 'Dell XPS 15',
      description: 'High-performance laptop for professionals with Intel i7 and 16GB RAM.',
      price: 1399.99,
      stock_quantity: 10,
      category_id: 'desktops',
      brand: 'Dell',
      sku: 'DLL-XPS15',
      is_active: true,
      image: '/products/dellxps15.png',
      created_at: '2024-01-15T14:30:00Z',
      updated_at: '2024-04-01T12:00:00Z',
    },
    {
      id: '3',
      name: 'Sony PlayStation 5',
      description: 'Next-gen console with lightning-fast load times and stunning graphics.',
      price: 499.99,
      stock_quantity: 0,
      category_id: 'gaming',
      brand: 'Sony',
      sku: 'SNY-PS5',
      is_active: true,
      image: '/products/ps5.png',
      created_at: '2023-11-10T08:45:00Z',
      updated_at: '2024-04-01T12:00:00Z',
    },
    {
      id: '4',
      name: 'Samsung Galaxy Tab S8',
      description: 'Ultra-thin tablet with a powerful processor and stunning AMOLED display.',
      price: 749.99,
      stock_quantity: 7,
      category_id: 'tablets',
      brand: 'Samsung',
      sku: 'SMS-TABS8',
      is_active: true,
      image: '/products/galaxytabs8.png',
      created_at: '2024-02-20T13:00:00Z',
      updated_at: '2024-04-01T12:00:00Z',
    },
    {
        id: '1',
        name: 'iPhone 14 Pro Max',
        description: 'Apple’s latest iPhone with A16 Bionic chip and triple camera setup.',
        price: 1099.99,
        stock_quantity: 25,
        category_id: 'mobiles',
        brand: 'Apple',
        sku: 'APL-IP14PM',
        is_active: true,
        image: '/products/iphone14.png',
        created_at: '2024-01-01T10:00:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '2',
        name: 'Dell XPS 15',
        description: 'High-performance laptop for professionals with Intel i7 and 16GB RAM.',
        price: 1399.99,
        stock_quantity: 10,
        category_id: 'desktops',
        brand: 'Dell',
        sku: 'DLL-XPS15',
        is_active: true,
        image: '/products/dellxps15.png',
        created_at: '2024-01-15T14:30:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '3',
        name: 'Sony PlayStation 5',
        description: 'Next-gen console with lightning-fast load times and stunning graphics.',
        price: 499.99,
        stock_quantity: 0,
        category_id: 'gaming',
        brand: 'Sony',
        sku: 'SNY-PS5',
        is_active: true,
        image: '/products/ps5.png',
        created_at: '2023-11-10T08:45:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '4',
        name: 'Samsung Galaxy Tab S8',
        description: 'Ultra-thin tablet with a powerful processor and stunning AMOLED display.',
        price: 749.99,
        stock_quantity: 7,
        category_id: 'tablets',
        brand: 'Samsung',
        sku: 'SMS-TABS8',
        is_active: true,
        image: '/products/galaxytabs8.png',
        created_at: '2024-02-20T13:00:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '1',
        name: 'iPhone 14 Pro Max',
        description: 'Apple’s latest iPhone with A16 Bionic chip and triple camera setup.',
        price: 1099.99,
        stock_quantity: 25,
        category_id: 'mobiles',
        brand: 'Apple',
        sku: 'APL-IP14PM',
        is_active: true,
        image: '/products/iphone14.png',
        created_at: '2024-01-01T10:00:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '2',
        name: 'Dell XPS 15',
        description: 'High-performance laptop for professionals with Intel i7 and 16GB RAM.',
        price: 1399.99,
        stock_quantity: 10,
        category_id: 'desktops',
        brand: 'Dell',
        sku: 'DLL-XPS15',
        is_active: true,
        image: '/products/dellxps15.png',
        created_at: '2024-01-15T14:30:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '3',
        name: 'Sony PlayStation 5',
        description: 'Next-gen console with lightning-fast load times and stunning graphics.',
        price: 499.99,
        stock_quantity: 0,
        category_id: 'gaming',
        brand: 'Sony',
        sku: 'SNY-PS5',
        is_active: true,
        image: '/products/ps5.png',
        created_at: '2023-11-10T08:45:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
      {
        id: '4',
        name: 'Samsung Galaxy Tab S8',
        description: 'Ultra-thin tablet with a powerful processor and stunning AMOLED display.',
        price: 749.99,
        stock_quantity: 7,
        category_id: 'tablets',
        brand: 'Samsung',
        sku: 'SMS-TABS8',
        is_active: true,
        image: '/products/galaxytabs8.png',
        created_at: '2024-02-20T13:00:00Z',
        updated_at: '2024-04-01T12:00:00Z',
      },
  ];
  